import 'package:flutter_web/modules/classMedicen.dart';

enum Order_status { preparation, sent, resive }

class Order {
  int id;
  String nameUser;
  Order_status orderStatus;
  bool money;
  List<Medicen> medicen;
  Order(this.id, this.nameUser, this.orderStatus, this.money, this.medicen);
}

List<Order> orders = [
  Order(1, "abd", Order_status.preparation, false, [
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
  ]),
  Order(2, "ans", Order_status.resive, true, [
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
  ]),
  Order(3, "smr", Order_status.sent, false, [
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
  ]),
  Order(4, "abd", Order_status.sent, false, [
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
  ]),
  Order(5, "ans", Order_status.resive, true, [
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
  ]),
  Order(6, "smr", Order_status.sent, false, [
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
  ]),
  Order(7, "abd", Order_status.sent, false, [
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
  ]),
  Order(8, "ans", Order_status.preparation, true, [
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
  ]),
  Order(9, "smr", Order_status.sent, true, [
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
    Medicen(
      1,
      "scientificName",
      "commercialName",
      ["Analgesic", "Herbs"],
      "Manufacturer",
      10,
      DateTime.utc(1989, 11, 9),
      100,
      "assest/images/drug.png",
    ),
  ]),
];
